### ISSUE TITLE
No Properties Displaying

### ISSUE THREAD

**Issue by MacStevins** [henke37/window-follower#3]
I have an issue about version 0.2.0 on OBS version 26.1.1 where the properties doesn't show, even after reopening the Filters window and OBS itself. I've also used the latest version 0.4.0

OBS Log on 0.2.0:
> 18:02:10.534: CPU Name: Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
18:02:10.534: CPU Speed: 3399MHz
18:02:10.534: Physical Cores: 4, Logical Cores: 4
18:02:10.534: Physical Memory: 11204MB Total, 2240MB Free
18:02:10.534: Windows Version: 10.0 Build 19042 (release: 2009; revision: 1165; 64-bit)
18:02:10.534: Running as administrator: false
18:02:10.534: Aero is Enabled (Aero is always on for windows 8 and above)
18:02:10.534: Windows 10 Gaming Features:
18:02:10.535: 	Game DVR: On
18:02:10.535: 	Hardware GPU Scheduler: Off
18:02:10.537: Sec. Software Status:
18:02:10.538: 	Microsoft Defender Antivirus: enabled (AV)
18:02:10.539: 	Windows Firewall: enabled (FW)
18:02:10.539: Current Date/Time: 2021-09-15, 18:02:10
18:02:10.539: Browser Hardware Acceleration: true
18:02:10.539: Portable mode: false
18:02:10.890: OBS 26.1.1 (64-bit, windows)
18:02:10.890: ---------------------------------
18:02:10.891: ---------------------------------
18:02:10.891: audio settings reset:
18:02:10.891: 	samples per sec: 44100
18:02:10.891: 	speakers:        2
18:02:10.893: ---------------------------------
18:02:10.893: Initializing D3D11...
18:02:10.893: Available Video Adapters: 
18:02:10.895: 	Adapter 0: NVIDIA GeForce GTX 1050 Ti
18:02:10.895: 	  Dedicated VRAM: 4213178368
18:02:10.895: 	  Shared VRAM:    1579624448
18:02:10.895: 	  PCI ID:         10de:1c82
18:02:10.895: 	  Driver Version: 30.0.14.7196
18:02:10.896: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=PHL 234E5
18:02:10.896: 	  output 1: pos={1920, 0}, size={1920, 1080}, attached=true, refresh=50, name=SONY TV
18:02:10.898: Loading up D3D11 on adapter NVIDIA GeForce GTX 1050 Ti (0)
18:02:11.011: D3D11 loaded successfully, feature level used: b000
18:02:11.011: DXGI increase maximum frame latency success
18:02:11.011: D3D11 GPU priority setup failed (not admin?)
18:02:11.631: ---------------------------------
18:02:11.631: video settings reset:
18:02:11.631: 	base resolution:   1920x1080
18:02:11.631: 	output resolution: 1280x720
18:02:11.631: 	downscale filter:  Bicubic
18:02:11.631: 	fps:               30/1
18:02:11.631: 	format:            NV12
18:02:11.631: 	YUV mode:          709/Partial
18:02:11.631: NV12 texture support enabled
18:02:11.633: Audio monitoring device:
18:02:11.633: 	name: Default
18:02:11.633: 	id: default
18:02:11.635: ---------------------------------
18:02:11.641: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
18:02:11.641: Failed to load 'en-US' text for module: 'decklink-captions.dll'
18:02:11.642: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
18:02:11.676: [AMF] Unable to load 'amfrt64.dll', error code 126.
18:02:11.678: [AMF] AMF Test failed due to one or more errors.
18:02:11.678: Failed to initialize module 'enc-amf.dll'
18:02:11.686: LoadLibrary failed for 'C:/Users/rvchi/AppData/Local/Programs/Python/Python39/python36.dll': The specified module could not be found.
18:02:11.686:  (126)
18:02:11.686: [Python] Could not load library: C:/Users/rvchi/AppData/Local/Programs/Python/Python39/python36.dll
18:02:11.699: [obs-browser]: Version 2.9.1
18:02:11.699: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
18:02:11.704: NVENC supported
18:02:11.866: Couldn't find VLC installation, VLC video source disabled
18:02:11.875: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
18:02:11.876: No blackmagic support
18:02:11.883: ---------------------------------
18:02:11.883:   Loaded Modules:
18:02:11.883:     window-follower.dll
18:02:11.883:     win-wasapi.dll
18:02:11.883:     win-mf.dll
18:02:11.883:     win-dshow.dll
18:02:11.883:     win-decklink.dll
18:02:11.883:     win-capture.dll
18:02:11.883:     vlc-video.dll
18:02:11.883:     text-freetype2.dll
18:02:11.883:     rtmp-services.dll
18:02:11.883:     obs-x264.dll
18:02:11.883:     obs-vst.dll
18:02:11.883:     obs-transitions.dll
18:02:11.883:     obs-text.dll
18:02:11.883:     obs-qsv11.dll
18:02:11.883:     obs-outputs.dll
18:02:11.883:     obs-filters.dll
18:02:11.883:     obs-ffmpeg.dll
18:02:11.883:     obs-browser.dll
18:02:11.883:     image-source.dll
18:02:11.883:     frontend-tools.dll
18:02:11.883:     enc-amf.dll
18:02:11.883:     decklink-ouput-ui.dll
18:02:11.883:     decklink-captions.dll
18:02:11.883:     coreaudio-encoder.dll
18:02:11.883: ---------------------------------
18:02:11.883: ==== Startup complete ===============================================
18:02:11.890: All scene data cleared
18:02:11.890: ------------------------------------------------
18:02:11.912: [window-capture: 'Eclipse'] update settings:
18:02:11.912: 	executable: eclipse.exe
18:02:11.912: 	method selected: WGC
18:02:11.912: 	method chosen: WGC
18:02:11.912: 
18:02:11.912: [duplicator-monitor-capture: '1st Display'] update settings:
18:02:11.912: 	display: 1 (1920x1080)
18:02:11.912: 	cursor: true
18:02:11.921: Switched to scene 'Eclipse and Its App'
18:02:11.921: ------------------------------------------------
18:02:11.921: Loaded scenes:
18:02:11.921: - scene 'Main Scene':
18:02:11.921:     - source: '1st Display' (monitor_capture)
18:02:11.921: - scene 'Eclipse and Its App':
18:02:11.921:     - source: 'Eclipse' (window_capture)
18:02:11.921: ------------------------------------------------
18:03:04.947: User added source 'Window Capture' (window_capture) to scene 'Eclipse and Its App'
18:03:04.968: [window-capture: 'Window Capture'] update settings:
18:03:04.968: 	executable: chrome.exe
18:03:04.968: 	method selected: Automatic
18:03:04.968: 	method chosen: WGC
18:03:04.968: 
18:03:08.168: [window-capture: 'Window Capture'] update settings:
18:03:08.168: 	executable: javaw.exe
18:03:08.168: 	method selected: Automatic
18:03:08.168: 	method chosen: BitBlt
18:03:08.168: 

OBS Log on 0.4.0:
>18:22:57.760: CPU Name: Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
18:22:57.760: CPU Speed: 3399MHz
18:22:57.760: Physical Cores: 4, Logical Cores: 4
18:22:57.760: Physical Memory: 11204MB Total, 2802MB Free
18:22:57.760: Windows Version: 10.0 Build 19042 (release: 2009; revision: 1165; 64-bit)
18:22:57.760: Running as administrator: false
18:22:57.760: Aero is Enabled (Aero is always on for windows 8 and above)
18:22:57.760: Windows 10 Gaming Features:
18:22:57.760: 	Game DVR: On
18:22:57.760: 	Hardware GPU Scheduler: Off
18:22:57.762: Sec. Software Status:
18:22:57.763: 	Microsoft Defender Antivirus: enabled (AV)
18:22:57.764: 	Windows Firewall: enabled (FW)
18:22:57.764: Current Date/Time: 2021-09-15, 18:22:57
18:22:57.764: Browser Hardware Acceleration: true
18:22:57.764: Portable mode: false
18:22:58.112: OBS 26.1.1 (64-bit, windows)
18:22:58.112: ---------------------------------
18:22:58.113: ---------------------------------
18:22:58.113: audio settings reset:
18:22:58.113: 	samples per sec: 44100
18:22:58.113: 	speakers:        2
18:22:58.115: ---------------------------------
18:22:58.115: Initializing D3D11...
18:22:58.115: Available Video Adapters: 
18:22:58.118: 	Adapter 0: NVIDIA GeForce GTX 1050 Ti
18:22:58.118: 	  Dedicated VRAM: 4213178368
18:22:58.118: 	  Shared VRAM:    1579624448
18:22:58.118: 	  PCI ID:         10de:1c82
18:22:58.118: 	  Driver Version: 30.0.14.7196
18:22:58.118: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=PHL 234E5
18:22:58.118: 	  output 1: pos={1920, 0}, size={1920, 1080}, attached=true, refresh=50, name=SONY TV
18:22:58.121: Loading up D3D11 on adapter NVIDIA GeForce GTX 1050 Ti (0)
18:22:58.235: D3D11 loaded successfully, feature level used: b000
18:22:58.235: DXGI increase maximum frame latency success
18:22:58.235: D3D11 GPU priority setup failed (not admin?)
18:22:58.791: ---------------------------------
18:22:58.791: video settings reset:
18:22:58.791: 	base resolution:   1920x1080
18:22:58.791: 	output resolution: 1280x720
18:22:58.791: 	downscale filter:  Bicubic
18:22:58.791: 	fps:               30/1
18:22:58.791: 	format:            NV12
18:22:58.791: 	YUV mode:          709/Partial
18:22:58.792: NV12 texture support enabled
18:22:58.794: Audio monitoring device:
18:22:58.794: 	name: Default
18:22:58.794: 	id: default
18:22:58.796: ---------------------------------
18:22:58.802: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
18:22:58.802: Failed to load 'en-US' text for module: 'decklink-captions.dll'
18:22:58.803: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
18:22:58.839: [AMF] Unable to load 'amfrt64.dll', error code 126.
18:22:58.842: [AMF] AMF Test failed due to one or more errors.
18:22:58.842: Failed to initialize module 'enc-amf.dll'
18:22:58.850: LoadLibrary failed for 'C:/Users/rvchi/AppData/Local/Programs/Python/Python39/python36.dll': The specified module could not be found.
18:22:58.850:  (126)
18:22:58.850: [Python] Could not load library: C:/Users/rvchi/AppData/Local/Programs/Python/Python39/python36.dll
18:22:58.865: [obs-browser]: Version 2.9.1
18:22:58.865: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
18:22:58.869: NVENC supported
18:22:59.045: Couldn't find VLC installation, VLC video source disabled
18:22:59.054: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
18:22:59.055: No blackmagic support
18:22:59.064: ---------------------------------
18:22:59.064:   Loaded Modules:
18:22:59.064:     window-follower.dll
18:22:59.064:     win-wasapi.dll
18:22:59.064:     win-mf.dll
18:22:59.064:     win-dshow.dll
18:22:59.064:     win-decklink.dll
18:22:59.064:     win-capture.dll
18:22:59.064:     vlc-video.dll
18:22:59.064:     text-freetype2.dll
18:22:59.064:     rtmp-services.dll
18:22:59.064:     obs-x264.dll
18:22:59.064:     obs-vst.dll
18:22:59.064:     obs-transitions.dll
18:22:59.064:     obs-text.dll
18:22:59.064:     obs-qsv11.dll
18:22:59.064:     obs-outputs.dll
18:22:59.064:     obs-filters.dll
18:22:59.064:     obs-ffmpeg.dll
18:22:59.064:     obs-browser.dll
18:22:59.064:     image-source.dll
18:22:59.064:     frontend-tools.dll
18:22:59.064:     enc-amf.dll
18:22:59.064:     decklink-ouput-ui.dll
18:22:59.064:     decklink-captions.dll
18:22:59.064:     coreaudio-encoder.dll
18:22:59.064: ---------------------------------
18:22:59.065: ==== Startup complete ===============================================
18:22:59.071: All scene data cleared
18:22:59.071: ------------------------------------------------
18:22:59.096: [window-capture: 'Window Capture'] update settings:
18:22:59.096: 	executable: explorer.exe
18:22:59.096: 	method selected: Automatic
18:22:59.096: 	method chosen: BitBlt
18:22:59.096: 
18:22:59.097: [window-capture: 'Eclipse'] update settings:
18:22:59.097: 	executable: eclipse.exe
18:22:59.097: 	method selected: WGC
18:22:59.097: 	method chosen: WGC
18:22:59.097: 
18:22:59.098: [duplicator-monitor-capture: '1st Display'] update settings:
18:22:59.098: 	display: 1 (1920x1080)
18:22:59.098: 	cursor: true
18:22:59.105: Switched to scene 'Eclipse and Its App'
18:22:59.105: ------------------------------------------------
18:22:59.105: Loaded scenes:
18:22:59.105: - scene 'Main Scene':
18:22:59.105:     - source: '1st Display' (monitor_capture)
18:22:59.105: - scene 'Eclipse and Its App':
18:22:59.105:     - source: 'Eclipse' (window_capture)
18:22:59.105:     - source: 'Window Capture' (window_capture)
18:22:59.105:         - filter: 'Window follower' (window-follower)
18:22:59.105: ------------------------------------------------
18:23:07.510: User Removed source 'Window Capture' (window_capture) from scene 'Eclipse and Its App'
18:23:09.905: User added scene 'Scene 2'
18:23:09.905: User switched to scene 'Scene 2'
18:23:13.166: User added source 'Window Capture' (window_capture) to scene 'Scene 2'
18:23:13.196: [window-capture: 'Window Capture'] update settings:
18:23:13.196: 	executable: chrome.exe
18:23:13.196: 	method selected: Automatic
18:23:13.196: 	method chosen: WGC
18:23:13.196: 
18:23:15.596: [window-capture: 'Window Capture'] update settings:
18:23:15.596: 	executable: Messenger.exe
18:23:15.596: 	method selected: Automatic
18:23:15.596: 	method chosen: WGC
18:23:15.596: 
18:23:18.329: [window-capture: 'Window Capture'] update settings:
18:23:18.329: 	executable: explorer.exe
18:23:18.329: 	method selected: Automatic
18:23:18.329: 	method chosen: BitBlt
18:23:18.329: 
18:23:25.095: User added filter 'Window follower' (window-follower) to source 'Window Capture'

**Comment by henke37** [comment]
The filter goes on the scene, not the captured source.
