### ISSUE TITLE
[Feature request] Allow it to mask out areas of the window that are behind other windows on the desktop.

### ISSUE THREAD

**Issue by ItsCubeTime** [henke37/window-follower#6]
I feel the most common usecase of this is to censor certain windows - which is at least what I use it for, however its somewhat annoying then that if you have a window open in the background, it will also censor/draw-on-top the window that window follower is set to track making whatever you are really looking at "censored"/filtered inadequately.

**Comment by henke37** [comment]
This is out of scope for this plugin.
